"""Initial migration

Revision ID: 79aeb9b232c4
Revises: 
Create Date: 2026-02-25 16:00:15.796837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79aeb9b232c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Обновляем существующие данные к правильным значениям Enum
    op.execute("UPDATE participants SET positions = 'GOALKEEPER' WHERE positions = 'goalkeeper'")
    op.execute("UPDATE participants SET positions = 'DEFENDER' WHERE positions = 'defender'")
    op.execute("UPDATE participants SET positions = 'MIDFIELDER' WHERE positions = 'midfielder'")
    op.execute("UPDATE participants SET positions = 'FORWARD' WHERE positions = 'forward'")
    op.execute("UPDATE participants SET positions = 'FREEDRAWER' WHERE positions = 'free_drawer' OR positions = 'FREE_DRAWER'")
    op.execute("UPDATE participants SET positions = 'NOPOSITION' WHERE positions = 'no_position' OR positions = 'NO_POSITION'")
    
    # Создаем тип Enum через SQL
    op.execute("CREATE TYPE participantpostion AS ENUM ('GOALKEEPER', 'DEFENDER', 'MIDFIELDER', 'FORWARD', 'FREEDRAWER', 'NOPOSITION')")
    
    # Затем изменяем колонку
    op.execute("ALTER TABLE participants ALTER COLUMN positions TYPE participantpostion USING positions::text::participantpostion")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем колонку к VARCHAR
    op.execute("ALTER TABLE participants ALTER COLUMN positions TYPE VARCHAR USING positions::text")
    
    # Удаляем тип Enum
    op.execute("DROP TYPE participantpostion")
    # ### end Alembic commands ###
